# This shared workflow cannot be called from a public repository. is because of reasons. Maybe we can fix this in the future.

# name: Maybe Create a Release

#on: 
#  push:
#    branches:
#      - main
#jobs:
#  run-release-workflow:
#    uses: pie/.github/.github/workflows/release.yaml@main